sscs-tribunals:
  ingressHost: chart-sscs-tribunals-release.service.core-compute-preview.internal
  ingressIP: "10.97.16.227"
  consulIP: "10.97.11.254"
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-tribunals
    REFORM_ENVIRONMENT: preview
  apiGateway:
    s2sKey: "AAAAAAAAAAAAAAAA"
    idamClientSecret: "123456"

  dataStoreApi:
    s2sKey: "AAAAAAAAAAAAAAAA"

  definitionStoreApi:
    s2sKey: "AAAAAAAAAAAAAAAA"

global:
  subscriptionId: "1c4f0704-a29e-403d-b719-b90c34ef14c9"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat