global:
  environment: aat
  subscriptionId: "1c4f0704-a29e-403d-b719-b90c34ef14c9"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### SSCS SERVICES ###
sscs-tribunals-frontend:
  nodejs:
    image: hmcts.azurecr.io/hmcts/sscs-tribunals-frontend:latest
    readinessDelay: 180 # let backends all start
    livenessDelay: 180 # let backends all start
    registerAdditionalDns:
      enabled: false
    environment:
      CHART: true

sscs-tribunals-api:
  java:
    releaseNameOverride: sscs-tya-frontend
    image: hmcts.azurecr.io/hmcts/sscs-tya-frontend:latest
    readinessDelay: 120 # plenty time for dependencies all start
    livenessDelay: 120 # plenty time for dependencies all start
    environment:
      CHART: true

sscs-tya-frontend:
  nodejs:
    releaseNameOverride: sscs-tya-frontend
    image: hmcts.azurecr.io/hmcts/sscs-tya-frontend:latest
    readinessDelay: 180 # let backends all start
    livenessDelay: 180 # let backends all start
    registerAdditionalDns:
      enabled: false
    environment:
      - CHART: true
########################

##### DEPENDENCIES #####
cmc-pdf-service:
  java:
    releaseNameOverride: cmc-pdf-service
    image: hmcts.azurecr.io/hmcts/cmc-pdf-service:latest

rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-sscs-rpe-service-auth-provider
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest