global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### SSCS SERVICES ###
sscs-tribunals-api:
  java:
    releaseNameOverride: sscs-tya-frontend
    image: hmcts.azurecr.io/hmcts/sscs-tya-frontend:latest
    readinessDelay: 120 # plenty time for dependencies all start
    livenessDelay: 120 # plenty time for dependencies all start
    environment:
      SERVER_PORT: 8080
      REFORM_TEAM: sscs
      REFORM_SERVICE_NAME: sscs-tribunals-case-api
      REFORM_SERVICE_TYPE: java
      REFORM_ENVIRONMENT: preview
      IDAM_API_URL: ${IDAM_API_URL}
      EMAIL_FROM: "sscs@hmcts.net"
      EMAIL_TO: "sscstest@greencroftconsulting.com"
      EMAIL_SUBJECT: "Your appeal"
      EMAIL_MESSAGE: "Your appeal has been created. Please do not respond to this email"
      ROBOTICS_EMAIL_FROM: "sscs@hmcts.net"
      ROBOTICS_EMAIL_TO: "fake"
      ROBOTICS_EMAIL_SUBJECT: "Robotics Data"
      ROBOTICS_EMAIL_MESSAGE: "Please find attached the robotics json file \nPlease do not respond to this email"
      EMAIL_SERVER_HOST: "mta.reform.hmcts.net"
      EMAIL_SERVER_PORT: "25"
      EMAIL_SMTP_TLS_ENABLED: "true"
      EMAIL_SMTP_SSL_TRUST: "*"
      PDF_API_URL: "http://cmc-pdf-service"
      SUBSCRIPTIONS_MAC_SECRET: ${SUBSCRIPTIONS_MAC_SECRET}
      CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
      CORE_CASE_DATA_JURISDICTION_ID: "SSCS"
      CORE_CASE_DATA_CASE_TYPE_ID: "Benefit"
      IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
      IDAM_S2S_AUTH: "http://rpe-service-auth-provider"
      IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
      IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
      IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
      IDAM_OAUTH2_CLIENT_ID: "sscs"
      IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
      IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
      DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
      MAX_FILE_SIZE: "10MB"
      MAX_REQUEST_SIZE: "10MB"
      ROOT_LOGGING_LEVEL: INFO
      LOG_OUTPUT: single


sscs-tya-frontend:
  nodejs:
    releaseNameOverride: sscs-tya-frontend
    image: hmcts.azurecr.io/hmcts/sscs-tya-frontend:latest
    readinessDelay: 180 # let backends all start
    livenessDelay: 180 # let backends all start
    registerAdditionalDns:
      enabled: false
    environment:
      PUBLIC_PROTOCOL: https
      REFORM_TEAM: sscs
      REFORM_SERVICE_NAME: sscs-track-your-appeal-frontend
      REFORM_ENVIRONMENT : preview
      SSCS_API_URL: http://sscs-tribunals-api-aat.service.core-compute-aat.internal
      COOKIE_SECRET:
      NODE_ENV: preview
  rpe-feature-toggle-api:
    releaseNameOverride: ftr-tgl-api
    importer:
      oneoff:
        command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0' ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST} &&
          /scripts/add-toggle.sh cmc_defence_reminders 'CMC defence reminders' false ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST}
    java:
      releaseNameOverride: ftr-tgl-api
      environment:
        FEATURES_DB_HOST: cmc-postgres
########################

##### DEPENDENCIES #####
cmc-pdf-service:
  java:
    releaseNameOverride: cmc-pdf-service
    image: hmcts.azurecr.io/hmcts/cmc-pdf-service:latest

rpe-service-auth-provider:
  java:
    releaseNameOverride: rpe-service-auth-provider
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest
